# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.0’

target 'hw9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.4'
	pod 'SwiftyJSON'
	pod "SwiftSpinner"
	pod "EasyToast"
	pod “FBSDKCoreKit”
	pod “FBSDKShareKit”
	pod “FBSDKLoginKit”

end
